service: budget-tagger

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: ${opt:region, 'eu-central-1'}
  stage: ${opt:stage, 'dev'}
  
  environment:
    STAGE: ${self:provider.stage}
    REGION: ${self:provider.region}
  
  # Use existing IAM role instead of creating one
  # iam:
  #   role:
  #     statements:
  #       # IAM permissions TBD

package:
  individually: true

functions:
  telegramIngress:
    handler: src/handlers/telegram-ingress.handler
    events:
      - http:
          path: telegram/ingress
          method: post
          cors: true
plugins:
  - serverless-plugin-typescript
  - serverless-offline
